FROM node:18-alpine
WORKDIR /app

COPY package*.json ./
COPY leadpulse-data-model/package*.json ./leadpulse-data-model/
COPY leadpulse-import-service/package*.json ./leadpulse-import-service/

RUN npm ci

COPY leadpulse-data-model ./leadpulse-data-model
COPY leadpulse-import-service ./leadpulse-import-service

CMD ["npm", "start", "-w", "leadpulse-import-service"]