const fs = require('fs');
const path = require('path');
const logger = require('./logger');

// MVP Storage Abstraction (Local Disk)
class StorageService {
  constructor() {
    this.uploadDir = path.resolve(__dirname, '../../../uploads');
    if (!fs.existsSync(this.uploadDir)) {
      fs.mkdirSync(this.uploadDir, { recursive: true });
    }
  }

  async uploadFile(file, prefix = 'import') {
    // In production, this would upload to S3 and return the S3 Object Key
    const fileKey = `${prefix}_${Date.now()}_${file.originalname.replace(/\s+/g, '_')}`;
    const destPath = path.join(this.uploadDir, fileKey);

    return new Promise((resolve, reject) => {
      fs.copyFile(file.path, destPath, (err) => {
        if (err) {
          logger.error('Failed to move uploaded file', { error: err });
          return reject(err);
        }
        // Clean up the temp file generated by multer
        fs.unlink(file.path, () => {});
        resolve(fileKey);
      });
    });
  }
}

module.exports = new StorageService();
